import type {
  Advertiser,
  ConciergeRequest,
  Deal,
  Lead,
  Payment,
  PaymentItem,
  PaymentMethod,
  ProductCode,
  Property,
  SearchEntry,
  Visit,
} from '../lib/types';
import { DEMO_USER, PRODUCTS } from '../lib/constants';
import { IMG } from './images';

const DAY = 864e5;
const daysAgo = (d: number, h = 10, m = 15) => {
  const x = new Date(Date.now() - d * DAY);
  x.setHours(h, m, 0, 0);
  return x.toISOString();
};
const hoursAgo = (h: number) => new Date(Date.now() - h * 36e5).toISOString();
const dateIn = (d: number) => {
  const x = new Date(Date.now() + d * DAY);
  if (x.getDay() === 0) x.setDate(x.getDate() + (d >= 0 ? 1 : -1));
  return `${x.getFullYear()}-${String(x.getMonth() + 1).padStart(2, '0')}-${String(x.getDate()).padStart(2, '0')}`;
};

/* ---------------- Anunciantes ---------------- */
export const ME_OWNER: Advertiser = {
  id: 'me-owner',
  name: DEMO_USER.name,
  type: 'proprietario',
  phone: DEMO_USER.phone,
  verified: true,
  since: '2025-03-01',
};
export const ME_BROKER: Advertiser = {
  id: 'me-broker',
  name: `${DEMO_USER.name} · Consultora`,
  type: 'intermediario',
  phone: DEMO_USER.phone,
  verified: true,
  since: '2024-11-01',
};
const POLANA_PRIME: Advertiser = { id: 'adv-polana', name: 'Polana Prime Imobiliária', type: 'agencia', phone: '+258 84 310 2200', verified: true, since: '2023-06-12' };
const BAIA_CORP: Advertiser = { id: 'adv-baia', name: 'Baía Corporate Real Estate', type: 'agencia', phone: '+258 85 220 4410', verified: true, since: '2024-01-20' };
const HELDER: Advertiser = { id: 'adv-helder', name: 'Hélder Macuácua', type: 'intermediario', phone: '+258 84 771 3090', verified: true, since: '2024-05-02' };
const ANABELA: Advertiser = { id: 'adv-anabela', name: 'Anabela Sitoe', type: 'intermediario', phone: '+258 86 402 1187', verified: true, since: '2024-09-15' };
const NELIO: Advertiser = { id: 'adv-nelio', name: 'Nélio Cossa', type: 'intermediario', phone: '+258 87 115 6620', verified: true, since: '2025-02-10' };
const SOFALA: Advertiser = { id: 'adv-sofala', name: 'Sofala Imóveis', type: 'agencia', phone: '+258 84 998 0045', verified: false, since: '2025-07-01' };
const CELIA: Advertiser = { id: 'adv-celia', name: 'Célia Mabunda', type: 'proprietario', phone: '+258 82 640 7712', verified: true, since: '2025-04-18' };
const EDSON: Advertiser = { id: 'adv-edson', name: 'Edson Muianga', type: 'intermediario', phone: '+258 84 203 5561', verified: true, since: '2024-12-03' };
const TEMBE: Advertiser = { id: 'adv-tembe', name: 'Tembe & Filhos, Lda', type: 'proprietario', phone: '+258 85 300 9988', verified: false, since: '2026-09-01' };
const LUISA: Advertiser = { id: 'adv-luisa', name: 'Luísa Nhantumbo', type: 'proprietario', phone: '+258 86 777 2301', verified: false, since: '2026-09-10' };

const base = {
  livingRoom: true,
  kitchen: true,
  balcony: false,
  furnished: false,
  hasTitle: true,
  hasLicense: true,
  immediate: true,
  negotiable: true,
  status: 'publicado' as Property['status'],
  verified: true,
  featured: false,
  highlights: [] as string[],
};
type BaseKeys = keyof typeof base;
const prop = (p: Omit<Property, BaseKeys> & Partial<Pick<Property, BaseKeys>>): Property => ({ ...base, ...p });

/* ---------------- Imóveis ---------------- */
export const SEED_PROPERTIES: Property[] = [
  prop({
    id: 'kh-1000',
    title: 'Villa contemporânea com piscina infinita na Costa do Sol',
    description:
      'Obra de autor sobre a encosta da Costa do Sol, com vista total para o Índico. Cinco suites, salas em pé-direito duplo que se abrem para a piscina infinita, cozinha de chef e cave com garrafeira. Domótica, energia solar com baterias, furo de água e segurança 24h. Uma das residências mais exclusivas de Maputo — visitas apenas para clientes qualificados.',
    type: 'Moradia',
    purpose: 'Venda',
    typology: 'V5+',
    neighborhood: 'Costa do Sol',
    city: 'Maputo',
    zone: 'Marginal / Frente mar',
    floor: 0,
    totalArea: 1400,
    usefulArea: 720,
    bedrooms: 5,
    bathrooms: 6,
    balcony: true,
    parking: 4,
    condition: 'Novo',
    furnished: true,
    price: 2450000,
    currency: 'USD',
    commission: 3,
    photos: [IMG.hero, IMG.bedroom, IMG.kitchen2, IMG.bath1, IMG.penthouse],
    video: 'tour-villa-costa-do-sol.mp4',
    lat: -25.9235,
    lng: 32.6205,
    featured: true,
    tier: 'Premium',
    advertiser: POLANA_PRIME,
    views: 4210,
    createdAt: daysAgo(6),
    verifiedAt: daysAgo(5),
    highlights: ['Vista mar total', 'Piscina infinita', 'Energia solar + baterias', 'Domótica', 'Segurança 24h'],
  }),
  prop({
    id: 'kh-1001',
    title: 'Apartamento T3 com vista mar na Polana',
    description:
      'Apartamento de acabamentos premium no 9.º andar, com vista desafogada sobre a baía de Maputo. Suite principal com closet, cozinha equipada, varanda corrida e dois lugares de estacionamento em cave. Condomínio com segurança 24h, gerador e ginásio — a dois minutos da Avenida Julius Nyerere.',
    type: 'Apartamento',
    purpose: 'Venda',
    typology: 'T3',
    neighborhood: 'Polana Cimento A',
    city: 'Maputo',
    zone: 'Zona nobre',
    floor: 9,
    totalArea: 210,
    usefulArea: 185,
    bedrooms: 3,
    bathrooms: 3,
    balcony: true,
    parking: 2,
    condition: 'Como novo',
    furnished: true,
    price: 385000,
    currency: 'USD',
    commission: 3,
    photos: [IMG.apartment, IMG.bedroom, IMG.kitchen1, IMG.bath2, IMG.room2],
    video: 'tour-polana-t3.mp4',
    lat: -25.9712,
    lng: 32.5968,
    featured: true,
    tier: 'Premium',
    advertiser: ME_BROKER,
    views: 1840,
    createdAt: daysAgo(3),
    verifiedAt: daysAgo(2),
    highlights: ['Vista mar', 'Gerador', 'Ginásio', 'Segurança 24h'],
  }),
  prop({
    id: 'kh-1002',
    title: 'Moradia V4 contemporânea com piscina no Sommerschield',
    description:
      'Moradia nova de arquitectura contemporânea numa das ruas mais tranquilas do Sommerschield. Quatro suites, sala ampla com ligação directa ao jardim tropical e piscina, cozinha em ilha, anexo para funcionários e garagem para quatro viaturas. Painéis solares, furo e cisterna de 20 mil litros.',
    type: 'Moradia',
    purpose: 'Venda',
    typology: 'V4',
    neighborhood: 'Sommerschield',
    city: 'Maputo',
    zone: 'Zona nobre',
    floor: 0,
    totalArea: 850,
    usefulArea: 420,
    bedrooms: 4,
    bathrooms: 5,
    balcony: true,
    parking: 4,
    condition: 'Novo',
    price: 1150000,
    currency: 'USD',
    commission: 3,
    photos: [IMG.villa, IMG.bedroom, IMG.kitchen3, IMG.bath1, IMG.apartment],
    video: 'tour-sommerschield-v4.mp4',
    lat: -25.9545,
    lng: 32.5958,
    featured: true,
    tier: 'Premium',
    advertiser: POLANA_PRIME,
    views: 2960,
    createdAt: daysAgo(9),
    verifiedAt: daysAgo(8),
    highlights: ['Piscina', 'Jardim tropical', 'Anexo', 'Painéis solares'],
  }),
  prop({
    id: 'kh-1003',
    title: 'Penthouse T4 com terraço panorâmico na Marginal',
    description:
      'Penthouse mobilada no último piso de um edifício novo na Marginal, com terraço de 90 m² virado ao mar. Ideal para executivos e contratos corporativos: quatro suites, escritório, lavandaria, três lugares de garagem e serviço de limpeza opcional.',
    type: 'Apartamento',
    purpose: 'Arrendamento',
    typology: 'T4',
    neighborhood: 'Costa do Sol',
    city: 'Maputo',
    zone: 'Marginal / Frente mar',
    floor: 14,
    totalArea: 380,
    usefulArea: 320,
    bedrooms: 4,
    bathrooms: 4,
    balcony: true,
    parking: 3,
    condition: 'Novo',
    furnished: true,
    price: 7500,
    currency: 'USD',
    negotiable: false,
    commission: 5,
    photos: [IMG.penthouse, IMG.apartment, IMG.bedroom, IMG.kitchen2, IMG.bath1],
    video: 'tour-penthouse-marginal.mp4',
    lat: -25.9335,
    lng: 32.6155,
    tier: 'Premium',
    advertiser: ME_BROKER,
    views: 1320,
    createdAt: daysAgo(4),
    verifiedAt: daysAgo(3),
    highlights: ['Terraço 90 m²', 'Mobilado', 'Contrato corporativo', 'Vista mar'],
  }),
  prop({
    id: 'kh-1004',
    title: 'Escritório premium open space na Baixa',
    description:
      'Piso inteiro de escritórios de classe A na Baixa, a poucos minutos dos principais bancos e ministérios. Open space com salas de reunião envidraçadas, copa, fibra óptica, gerador de edifício e seis lugares de estacionamento.',
    type: 'Escritório',
    purpose: 'Arrendamento',
    typology: 'Open space',
    neighborhood: 'Baixa',
    city: 'Maputo',
    zone: 'Centro / Baixa',
    floor: 6,
    totalArea: 320,
    usefulArea: 300,
    bedrooms: 0,
    bathrooms: 2,
    livingRoom: false,
    parking: 6,
    condition: 'Novo',
    furnished: true,
    price: 420000,
    currency: 'MZN',
    commission: 5,
    photos: [IMG.office, IMG.kitchen3, IMG.bath2],
    video: 'tour-escritorio-baixa.mp4',
    lat: -25.9698,
    lng: 32.5728,
    featured: true,
    tier: 'Premium',
    advertiser: BAIA_CORP,
    views: 870,
    createdAt: daysAgo(12),
    verifiedAt: daysAgo(11),
    highlights: ['Classe A', 'Fibra óptica', 'Gerador', '6 lugares'],
  }),
  prop({
    id: 'kh-1005',
    title: 'Terreno de 2 hectares frente mar na Ponta do Ouro',
    description:
      'Parcela rara com acesso directo à praia, a 10 minutos da vila da Ponta do Ouro. DUAT em nome do vendedor e estudo prévio para eco-resort aprovado. Ideal para investimento turístico ou residência privada.',
    type: 'Terreno na praia',
    purpose: 'Venda',
    typology: 'Não aplicável',
    neighborhood: 'Ponta do Ouro',
    city: 'Ponta do Ouro',
    zone: 'Zona turística',
    floor: 0,
    totalArea: 20000,
    usefulArea: 20000,
    bedrooms: 0,
    bathrooms: 0,
    livingRoom: false,
    kitchen: false,
    parking: 0,
    condition: 'Não aplicável',
    price: 420000,
    currency: 'USD',
    commission: 5,
    photos: [IMG.beach, IMG.beach2, IMG.beachhouse],
    video: 'drone-ponta-do-ouro.mp4',
    lat: -26.8385,
    lng: 32.8962,
    featured: true,
    tier: 'Oportunidade',
    advertiser: HELDER,
    views: 2210,
    createdAt: daysAgo(15),
    verifiedAt: daysAgo(14),
    highlights: ['DUAT em nome do vendedor', 'Acesso directo à praia', 'Estudo prévio aprovado'],
  }),
  prop({
    id: 'kh-1006',
    title: 'Eco-lodge operacional em Vilankulo, com vista para o Bazaruto',
    description:
      'Lodge em funcionamento com 12 chalés em macuti, restaurante, bar, piscina e centro de mergulho, virado ao arquipélago do Bazaruto. Licença de turismo em vigor, equipa formada e receita comprovada. Venda como negócio em funcionamento.',
    type: 'Lodge',
    purpose: 'Venda',
    typology: 'Não aplicável',
    neighborhood: 'Praia de Vilankulo',
    city: 'Vilankulo',
    zone: 'Zona turística',
    floor: 0,
    totalArea: 15000,
    usefulArea: 1800,
    bedrooms: 12,
    bathrooms: 14,
    balcony: true,
    parking: 15,
    condition: 'Bom estado',
    furnished: true,
    price: 1450000,
    currency: 'USD',
    commission: 4,
    photos: [IMG.lodge, IMG.bedroom, IMG.beach2, IMG.bath2, IMG.kitchen1],
    video: 'tour-lodge-vilankulo.mp4',
    lat: -21.992,
    lng: 35.3225,
    featured: true,
    tier: 'Premium',
    advertiser: POLANA_PRIME,
    views: 1675,
    createdAt: daysAgo(20),
    verifiedAt: daysAgo(19),
    highlights: ['Licença de turismo', 'Receita comprovada', '12 chalés', 'Centro de mergulho'],
  }),
  prop({
    id: 'kh-1007',
    title: 'Casa geminada T3 em condomínio fechado na Matola Rio',
    description:
      'Casa geminada nova num condomínio com segurança, parque infantil e zonas verdes. Três quartos (um em suite), sala e cozinha em open space, quintal privativo e dois lugares de estacionamento. Elegível para crédito à habitação.',
    type: 'Casa geminada',
    purpose: 'Venda',
    typology: 'T3',
    neighborhood: 'Matola Rio',
    city: 'Matola',
    zone: 'Zona residencial',
    floor: 0,
    totalArea: 300,
    usefulArea: 165,
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    condition: 'Novo',
    price: 8900000,
    currency: 'MZN',
    commission: 3,
    photos: [IMG.townhouse, IMG.kitchen3, IMG.room1, IMG.bath2],
    video: 'tour-matola-rio.mp4',
    lat: -26.0405,
    lng: 32.4418,
    tier: 'Essencial',
    advertiser: ME_OWNER,
    views: 940,
    createdAt: daysAgo(7),
    verifiedAt: daysAgo(6),
    highlights: ['Condomínio fechado', 'Parque infantil', 'Crédito habitação'],
  }),
  prop({
    id: 'kh-1008',
    title: 'Armazém logístico de 2.500 m² na Machava, junto à EN4',
    description:
      'Armazém moderno com pé-direito de 10 metros, quatro cais de carga, escritórios de apoio e pátio para manobra de camiões. Energia trifásica, posto de transformação próprio e acesso imediato à EN4 — corredor Maputo–Joanesburgo.',
    type: 'Armazém',
    purpose: 'Arrendamento',
    typology: 'Não aplicável',
    neighborhood: 'Machava',
    city: 'Matola',
    zone: 'Zona industrial',
    floor: 0,
    totalArea: 4000,
    usefulArea: 2500,
    bedrooms: 0,
    bathrooms: 4,
    livingRoom: false,
    kitchen: false,
    parking: 20,
    condition: 'Bom estado',
    price: 950000,
    currency: 'MZN',
    commission: 5,
    photos: [IMG.warehouse, IMG.yard2, IMG.office],
    video: 'tour-armazem-machava.mp4',
    lat: -25.9125,
    lng: 32.4875,
    tier: 'Premium',
    advertiser: BAIA_CORP,
    views: 610,
    createdAt: daysAgo(10),
    verifiedAt: daysAgo(9),
    highlights: ['Pé-direito 10 m', '4 cais de carga', 'Energia trifásica', 'Acesso EN4'],
  }),
  prop({
    id: 'kh-1009',
    title: 'Apartamento T2 renovado e mobilado na Coop',
    description:
      'T2 totalmente renovado num prédio tranquilo da Coop, perto de escolas, supermercados e da Avenida Vladimir Lenine. Cozinha equipada, ar condicionado em todas as divisões, varanda e lugar de estacionamento.',
    type: 'Apartamento',
    purpose: 'Arrendamento',
    typology: 'T2',
    neighborhood: 'Coop',
    city: 'Maputo',
    zone: 'Zona residencial',
    floor: 3,
    totalArea: 110,
    usefulArea: 95,
    bedrooms: 2,
    bathrooms: 2,
    balcony: true,
    parking: 1,
    condition: 'Como novo',
    furnished: true,
    price: 75000,
    currency: 'MZN',
    commission: 4,
    photos: [IMG.room2, IMG.kitchen1, IMG.room1, IMG.bath1],
    video: 'tour-coop-t2.mp4',
    lat: -25.9568,
    lng: 32.5812,
    tier: 'Essencial',
    advertiser: ME_OWNER,
    views: 1105,
    createdAt: daysAgo(5),
    verifiedAt: daysAgo(4),
    highlights: ['Renovado', 'Ar condicionado', 'Mobilado'],
  }),
  prop({
    id: 'kh-1010',
    title: 'Quinta de 5 hectares com casa principal em Marracuene',
    description:
      'Quinta produtiva a 35 minutos de Maputo, com casa principal V3, casa de caseiro, pomar de mangueiras e cajueiros, furo com bomba solar e acesso ao rio. Perfeita para agro-turismo ou refúgio de fim-de-semana.',
    type: 'Quinta',
    purpose: 'Venda',
    typology: 'V3',
    neighborhood: 'Bobole',
    city: 'Marracuene',
    zone: 'Zona rural',
    floor: 0,
    totalArea: 50000,
    usefulArea: 280,
    bedrooms: 3,
    bathrooms: 3,
    balcony: true,
    parking: 6,
    condition: 'Bom estado',
    price: 16500000,
    currency: 'MZN',
    commission: 4,
    photos: [IMG.farm1, IMG.farm2, IMG.bedroom, IMG.kitchen3],
    video: 'drone-quinta-marracuene.mp4',
    lat: -25.692,
    lng: 32.648,
    tier: 'Oportunidade',
    advertiser: ANABELA,
    views: 530,
    createdAt: daysAgo(18),
    verifiedAt: daysAgo(17),
    highlights: ['5 hectares', 'Pomar', 'Furo solar', 'Casa de caseiro'],
  }),
  prop({
    id: 'kh-1011',
    title: 'Loja de esquina na Avenida Julius Nyerere',
    description:
      'Loja de esquina com montra dupla numa das artérias mais movimentadas da Polana. Pronta a abrir: pavimento novo, casa de banho, ar condicionado e dois lugares de estacionamento à porta. Ideal para retalho premium, café ou clínica.',
    type: 'Loja',
    purpose: 'Arrendamento',
    typology: 'Não aplicável',
    neighborhood: 'Polana Cimento B',
    city: 'Maputo',
    zone: 'Zona nobre',
    floor: 0,
    totalArea: 140,
    usefulArea: 130,
    bedrooms: 0,
    bathrooms: 1,
    livingRoom: false,
    kitchen: false,
    parking: 2,
    condition: 'Como novo',
    price: 185000,
    currency: 'MZN',
    commission: 5,
    photos: [IMG.retail1, IMG.retail2, IMG.office],
    video: 'tour-loja-nyerere.mp4',
    lat: -25.9642,
    lng: 32.5908,
    tier: 'Essencial',
    advertiser: ME_BROKER,
    views: 720,
    createdAt: daysAgo(8),
    verifiedAt: daysAgo(7),
    highlights: ['Esquina', 'Montra dupla', 'Alto tráfego'],
  }),
  prop({
    id: 'kh-1012',
    title: 'Edifício histórico de 3 pisos para reabilitação na Baixa',
    description:
      'Edifício de traça colonial com fachada de valor histórico, varandas em ferro forjado e 750 m² úteis distribuídos por três pisos. Potencial para boutique hotel, escritórios ou apartamentos. Projecto de reabilitação preliminar disponível.',
    type: 'Imóvel para reabilitação',
    purpose: 'Venda',
    typology: 'Não aplicável',
    neighborhood: 'Baixa',
    city: 'Maputo',
    zone: 'Centro / Baixa',
    floor: 0,
    totalArea: 900,
    usefulArea: 750,
    bedrooms: 0,
    bathrooms: 3,
    balcony: true,
    parking: 0,
    condition: 'Para renovar',
    price: 290000,
    currency: 'USD',
    commission: 5,
    photos: [IMG.colonial1, IMG.colonial2, IMG.office],
    video: 'tour-edificio-baixa.mp4',
    lat: -25.9732,
    lng: 32.5702,
    tier: 'Oportunidade',
    advertiser: NELIO,
    views: 980,
    createdAt: daysAgo(14),
    verifiedAt: daysAgo(13),
    highlights: ['Fachada histórica', 'Potencial boutique hotel', '3 pisos'],
  }),
  prop({
    id: 'kh-1013',
    title: 'Salão de eventos com jardim na Ponta Gêa, Beira',
    description:
      'Salão para 400 convidados com jardim para cerimónias, cozinha industrial, camarins e parque privativo. Negócio com agenda preenchida — oportunidade para operador de eventos ou investidor.',
    type: 'Salão de eventos',
    purpose: 'Venda',
    typology: 'Não aplicável',
    neighborhood: 'Ponta Gêa',
    city: 'Beira',
    zone: 'Zona residencial',
    floor: 0,
    totalArea: 2400,
    usefulArea: 800,
    bedrooms: 0,
    bathrooms: 6,
    parking: 60,
    condition: 'Bom estado',
    furnished: true,
    hasLicense: false,
    price: 32000000,
    currency: 'MZN',
    commission: 4,
    photos: [IMG.event2, IMG.event1, IMG.kitchen3],
    video: 'tour-salao-beira.mp4',
    lat: -19.8395,
    lng: 34.842,
    verified: false,
    tier: 'Oportunidade',
    advertiser: SOFALA,
    views: 410,
    createdAt: daysAgo(11),
    highlights: ['400 convidados', 'Jardim', 'Cozinha industrial'],
  }),
  prop({
    id: 'kh-1014',
    title: 'Quarto mobilado com casa de banho privativa no Central',
    description:
      'Quarto amplo e mobilado num apartamento partilhado e bem cuidado, com casa de banho privativa, internet incluída e limpeza semanal. A 5 minutos a pé da Avenida Eduardo Mondlane.',
    type: 'Quarto',
    purpose: 'Arrendamento',
    typology: 'T0',
    neighborhood: 'Central',
    city: 'Maputo',
    zone: 'Centro / Baixa',
    floor: 2,
    totalArea: 18,
    usefulArea: 16,
    bedrooms: 1,
    bathrooms: 1,
    parking: 0,
    condition: 'Bom estado',
    furnished: true,
    negotiable: false,
    price: 18000,
    currency: 'MZN',
    commission: 2,
    photos: [IMG.room1, IMG.bath2, IMG.kitchen1],
    video: 'tour-quarto-central.mp4',
    lat: -25.9665,
    lng: 32.5795,
    verified: false,
    tier: 'Essencial',
    advertiser: CELIA,
    views: 350,
    createdAt: daysAgo(2),
    highlights: ['Internet incluída', 'WC privativo', 'Limpeza semanal'],
  }),
  prop({
    id: 'kh-1015',
    title: 'Casa de praia T3 no Tofo, a 50 m do mar',
    description:
      'Casa de praia com três quartos, varanda coberta e acesso por caminho privado à praia do Tofo. Excelente historial de arrendamento de curta duração — um investimento com rendimento em dólares.',
    type: 'Imóvel para investimento',
    purpose: 'Venda',
    typology: 'T3',
    neighborhood: 'Tofo',
    city: 'Inhambane',
    zone: 'Zona turística',
    floor: 0,
    totalArea: 600,
    usefulArea: 180,
    bedrooms: 3,
    bathrooms: 2,
    balcony: true,
    parking: 2,
    condition: 'Bom estado',
    furnished: true,
    price: 195000,
    currency: 'USD',
    commission: 4,
    photos: [IMG.beachhouse, IMG.beach2, IMG.bedroom, IMG.kitchen2],
    video: 'tour-tofo.mp4',
    lat: -23.8525,
    lng: 35.5465,
    tier: 'Oportunidade',
    advertiser: EDSON,
    views: 1290,
    createdAt: daysAgo(16),
    verifiedAt: daysAgo(15),
    highlights: ['50 m do mar', 'Rendimento em USD', 'Mobilada'],
  }),
  /* ---- Fila de validação ---- */
  prop({
    id: 'kh-1016',
    title: 'Estaleiro vedado de 6.000 m² na Matola Gare',
    description:
      'Estaleiro plano e vedado, com portão para camiões, contentores-escritório, casa de banho e ligação trifásica. Ideal para construtoras e logística ligeira.',
    type: 'Estaleiro',
    purpose: 'Arrendamento',
    typology: 'Não aplicável',
    neighborhood: 'Matola Gare',
    city: 'Matola',
    zone: 'Zona industrial',
    floor: 0,
    totalArea: 6000,
    usefulArea: 5800,
    bedrooms: 0,
    bathrooms: 1,
    livingRoom: false,
    kitchen: false,
    parking: 30,
    condition: 'Bom estado',
    price: 120000,
    currency: 'MZN',
    commission: 5,
    photos: [IMG.yard1, IMG.yard2, IMG.warehouse],
    video: 'estaleiro-matola-gare.mp4',
    lat: -25.8295,
    lng: 32.4505,
    status: 'em_validacao',
    verified: false,
    advertiser: TEMBE,
    views: 0,
    createdAt: hoursAgo(5),
  }),
  prop({
    id: 'kh-1017',
    title: 'Dependência T1 independente no Sommerschield',
    description:
      'Dependência independente com entrada própria, quarto, sala-kitchenette e casa de banho, num quintal arborizado do Sommerschield. Água e segurança incluídas.',
    type: 'Dependência',
    purpose: 'Arrendamento',
    typology: 'T1',
    neighborhood: 'Sommerschield',
    city: 'Maputo',
    zone: 'Zona nobre',
    floor: 0,
    totalArea: 55,
    usefulArea: 48,
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    condition: 'Como novo',
    furnished: true,
    hasLicense: false,
    price: 32000,
    currency: 'MZN',
    commission: 3,
    photos: [IMG.room2, IMG.kitchen1, IMG.bath1],
    video: 'dependencia-sommerschield.mp4',
    lat: -25.9528,
    lng: 32.5921,
    status: 'em_validacao',
    verified: false,
    advertiser: LUISA,
    views: 0,
    createdAt: hoursAgo(2),
  }),
  /* ---- Negócios fechados da carteira ---- */
  prop({
    id: 'kh-0901',
    title: 'Moradia V3 com quintal no Triunfo',
    description: 'Moradia V3 com quintal amplo e anexo, vendida através da KEYHOUSE.',
    type: 'Moradia',
    purpose: 'Venda',
    typology: 'V3',
    neighborhood: 'Triunfo',
    city: 'Maputo',
    zone: 'Zona residencial',
    floor: 0,
    totalArea: 600,
    usefulArea: 240,
    bedrooms: 3,
    bathrooms: 3,
    parking: 3,
    condition: 'Bom estado',
    price: 14500000,
    currency: 'MZN',
    commission: 3,
    photos: [IMG.townhouse, IMG.bedroom, IMG.kitchen3],
    video: 'tour-triunfo.mp4',
    lat: -25.9295,
    lng: 32.6105,
    status: 'vendido',
    advertiser: ME_BROKER,
    views: 1540,
    createdAt: daysAgo(40),
    verifiedAt: daysAgo(39),
  }),
  prop({
    id: 'kh-0902',
    title: 'Escritório de 180 m² na Polana',
    description: 'Escritório arrendado a empresa de consultoria através da KEYHOUSE.',
    type: 'Escritório',
    purpose: 'Arrendamento',
    typology: 'Open space',
    neighborhood: 'Polana Cimento A',
    city: 'Maputo',
    zone: 'Zona nobre',
    floor: 4,
    totalArea: 180,
    usefulArea: 170,
    bedrooms: 0,
    bathrooms: 2,
    livingRoom: false,
    parking: 3,
    condition: 'Como novo',
    furnished: true,
    price: 210000,
    currency: 'MZN',
    commission: 5,
    photos: [IMG.office, IMG.kitchen3, IMG.bath2],
    video: 'tour-escritorio-polana.mp4',
    lat: -25.9688,
    lng: 32.5941,
    status: 'arrendado',
    advertiser: ME_BROKER,
    views: 890,
    createdAt: daysAgo(30),
    verifiedAt: daysAgo(29),
  }),
];

/* ---------------- Leads ---------------- */
export const SEED_LEADS: Lead[] = [
  { id: 'l-01', propertyId: 'kh-1001', name: 'Sérgio Nhantumbo', phone: '+258 84 312 4578', email: 'sergio.n@email.co.mz', zone: 'Polana Cimento A', budget: 380000, currency: 'USD', bedrooms: 3, timeline: '30d', payment: 'credito_aprovado', score: 88, qualified: true, status: 'novo', feePaid: false, createdAt: hoursAgo(2) },
  { id: 'l-02', propertyId: 'kh-1003', name: 'Marta Oliveira', phone: '+258 85 610 2231', zone: 'Costa do Sol', budget: 7500, currency: 'USD', bedrooms: 4, timeline: 'imediato', payment: 'empresa', score: 95, qualified: true, status: 'aceite', feePaid: true, createdAt: daysAgo(1, 9) },
  { id: 'l-03', propertyId: 'kh-1007', name: 'Dércio Tembe', phone: '+258 86 229 4410', zone: 'Matola Rio', budget: 9000000, currency: 'MZN', bedrooms: 3, timeline: '90d', payment: 'credito_analise', score: 67, qualified: true, status: 'novo', feePaid: false, createdAt: hoursAgo(5) },
  { id: 'l-04', propertyId: 'kh-1009', name: 'Ana Cossa', phone: '+258 84 887 1204', zone: 'Coop', budget: 75000, currency: 'MZN', bedrooms: 2, timeline: 'imediato', payment: 'rendimento', score: 91, qualified: true, status: 'aceite', feePaid: true, createdAt: daysAgo(2, 14) },
  { id: 'l-05', propertyId: 'kh-1011', name: 'Nélio Bila', phone: '+258 87 340 1198', zone: 'Polana Cimento B', budget: 190000, currency: 'MZN', bedrooms: 0, timeline: '30d', payment: 'empresa', score: 84, qualified: true, status: 'novo', feePaid: false, createdAt: daysAgo(1, 16) },
  { id: 'l-06', propertyId: 'kh-1007', name: 'Telma Muianga', phone: '+258 82 401 7765', zone: 'Flexível', budget: 6000000, currency: 'MZN', bedrooms: 3, timeline: 'later', payment: 'nao_sei', score: 29, qualified: false, status: 'novo', feePaid: false, createdAt: daysAgo(1, 11) },
  { id: 'l-07', propertyId: 'kh-1001', name: 'Paulo Sitoe', phone: '+258 84 118 9032', zone: 'Sommerschield', budget: 250000, currency: 'USD', bedrooms: 3, timeline: '180d', payment: 'credito_analise', score: 38, qualified: false, status: 'novo', feePaid: false, createdAt: daysAgo(3, 10) },
  { id: 'l-08', propertyId: 'kh-1003', name: 'Ricardo Langa', phone: '+258 84 660 5521', zone: 'Costa do Sol', budget: 7000, currency: 'USD', bedrooms: 4, timeline: 'imediato', payment: 'empresa', score: 90, qualified: true, status: 'aceite', feePaid: true, createdAt: daysAgo(6, 15) },
  { id: 'l-09', propertyId: 'kh-1007', name: 'Helena Guambe', phone: '+258 85 902 3317', zone: 'Matola Rio', budget: 8900000, currency: 'MZN', bedrooms: 3, timeline: '30d', payment: 'pronto', score: 93, qualified: true, status: 'aceite', feePaid: true, createdAt: daysAgo(5, 12) },
  { id: 'l-10', propertyId: 'kh-1002', name: DEMO_USER.name, phone: DEMO_USER.phone, zone: 'Sommerschield', budget: 1150000, currency: 'USD', bedrooms: 4, timeline: '30d', payment: 'pronto', score: 96, qualified: true, status: 'aceite', feePaid: true, createdAt: daysAgo(2, 18), mine: true },
];

/* ---------------- Visitas ---------------- */
export const SEED_VISITS: Visit[] = [
  { id: 'v-01', leadId: 'l-02', propertyId: 'kh-1003', clientName: 'Marta Oliveira', clientPhone: '+258 85 610 2231', date: dateIn(1), time: '10:30', mode: 'presencial', status: 'confirmada', feePaid: true, reminderSent: true, createdAt: daysAgo(1, 9) },
  { id: 'v-02', leadId: 'l-04', propertyId: 'kh-1009', clientName: 'Ana Cossa', clientPhone: '+258 84 887 1204', date: dateIn(2), time: '15:30', mode: 'presencial', status: 'pendente', feePaid: false, createdAt: daysAgo(2, 14) },
  { id: 'v-03', leadId: 'l-01', propertyId: 'kh-1001', clientName: 'Sérgio Nhantumbo', clientPhone: '+258 84 312 4578', date: dateIn(3), time: '09:00', mode: 'presencial', status: 'pendente', feePaid: false, createdAt: hoursAgo(2) },
  { id: 'v-04', leadId: 'l-08', propertyId: 'kh-1003', clientName: 'Ricardo Langa', clientPhone: '+258 84 660 5521', date: dateIn(-2), time: '14:00', mode: 'presencial', status: 'realizada', feePaid: true, createdAt: daysAgo(6, 15) },
  { id: 'v-05', leadId: 'l-09', propertyId: 'kh-1007', clientName: 'Helena Guambe', clientPhone: '+258 85 902 3317', date: dateIn(-1), time: '10:30', mode: 'presencial', status: 'realizada', feePaid: true, createdAt: daysAgo(5, 12) },
  { id: 'v-06', leadId: 'l-10', propertyId: 'kh-1002', clientName: DEMO_USER.name, clientPhone: DEMO_USER.phone, date: dateIn(4), time: '11:00', mode: 'presencial', status: 'confirmada', feePaid: true, reminderSent: false, createdAt: daysAgo(2, 18), mine: true },
];

/* ---------------- Negócios ---------------- */
export const SEED_DEALS: Deal[] = [
  { id: 'd-01', propertyId: 'kh-0901', clientName: 'Família Chaúque', value: 14500000, currency: 'MZN', valueMZN: 14500000, commissionPct: 3, commissionMZN: 435000, vatMZN: 69600, brokerShareMZN: 261000, platformShareMZN: 174000, status: 'pago', createdAt: daysAgo(12) },
  { id: 'd-02', propertyId: 'kh-0902', clientName: 'Consultora Índico, Lda', value: 2520000, months: 12, currency: 'MZN', valueMZN: 2520000, commissionPct: 5, commissionMZN: 126000, vatMZN: 20160, brokerShareMZN: 75600, platformShareMZN: 50400, status: 'minuta', createdAt: daysAgo(3) },
];

/* ---------------- Pagamentos ---------------- */
const refOf = (iso: string, n: number) => {
  const d = new Date(iso);
  return `KH-${String(d.getFullYear()).slice(2)}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}-${n}`;
};
const pay = (
  id: string,
  createdAt: string,
  method: PaymentMethod,
  payer: string,
  list: [ProductCode, number, string?][],
  n: number,
): Payment => {
  const items: PaymentItem[] = list.map(([code, amount, ref]) => ({ code, label: PRODUCTS[code].label, amount, ref }));
  return { id, reference: refOf(createdAt, n), items, total: items.reduce((s, i) => s + i.amount, 0), method, payer, status: 'pago', createdAt };
};

export const SEED_PAYMENTS: Payment[] = [
  pay('pay-s01', hoursAgo(3), 'mpesa', 'Polana Prime Imobiliária', [['publicacao', 500, 'kh-1000'], ['destaque', 1500, 'kh-1000']], 4821),
  pay('pay-s02', hoursAgo(9), 'mpesa', 'Baía Corporate Real Estate', [['agencia', 10000]], 4790),
  pay('pay-s03', daysAgo(1, 12), 'emola', 'Hélder Macuácua', [['lead', 1000]], 4712),
  pay('pay-s04', daysAgo(1, 19), 'paypal', 'João Mucavele (Lisboa)', [['contacto', 200, 'kh-1002']], 4705),
  pay('pay-s05', daysAgo(2, 9), 'mpesa', 'Anabela Sitoe', [['visita', 500]], 4633),
  pay('pay-s06', daysAgo(2, 11), 'paypal', 'Família Guambe (Lisboa)', [['concierge', 5000, 'c-01']], 4630),
  pay('pay-s07', daysAgo(2, 16), 'mpesa', 'Célia Mabunda', [['publicacao', 500, 'kh-1014']], 4621),
  pay('pay-s08', daysAgo(3, 10), 'emola', 'Nélio Cossa', [['intermediario', 3000]], 4577),
  pay('pay-s09', daysAgo(4, 15), 'mpesa', 'Edson Muianga', [['destaque', 1500, 'kh-1015']], 4502),
  pay('pay-s10', daysAgo(5, 11), 'mpesa', 'Polana Prime Imobiliária', [['lead', 1000], ['lead', 1000], ['lead', 1000]], 4466),
  pay('pay-s11', daysAgo(5, 17), 'mpesa', 'Rui Chaúque', [['contacto', 200, 'kh-1006']], 4458),
  pay('pay-s12', daysAgo(6, 14), 'banco', 'Polana Prime Imobiliária', [['comissao', 504600, 'd-01']], 4401),
  pay('pay-s13', daysAgo(8, 10), 'emola', 'Sofala Imóveis', [['publicacao', 500, 'kh-1013']], 4312),
  pay('pay-s14', daysAgo(9, 9), 'mpesa', 'Hélder Macuácua', [['publicacao', 500, 'kh-1005'], ['destaque', 1500, 'kh-1005']], 4288),
];

export const SEED_SEARCHES: SearchEntry[] = [
  { id: 's-01', query: 'finalidade=Venda&cidade=Maputo&tipo=Apartamento&max=25000000', label: 'Apartamentos para venda em Maputo · até 25M MT', results: 1, createdAt: daysAgo(1, 21) },
  { id: 's-02', query: 'finalidade=Venda&q=Sommerschield&tipo=Moradia', label: 'Moradias para venda em Sommerschield', results: 1, createdAt: daysAgo(3, 20) },
  { id: 's-03', query: 'finalidade=Arrendamento&q=Coop&quartos=2', label: 'Imóveis para arrendar em Coop · 2+ quartos', results: 1, createdAt: daysAgo(6, 19) },
];

export const SEED_CONCIERGE: ConciergeRequest[] = [
  {
    id: 'c-01',
    name: 'Família Guambe (Lisboa)',
    phone: '+351 912 000 111',
    brief: 'Moradia V4 com jardim em Maputo (Sommerschield ou Triunfo), perto de escola internacional. Visitas por videochamada.',
    budget: 'USD 600.000',
    createdAt: daysAgo(2, 11),
    status: 'em_curso',
  },
];

/* ---------------- Métricas históricas (plataforma) ---------------- */
export type RevenueMonth = Record<ProductCode, number>;
export const REVENUE_HISTORY: RevenueMonth[] = [
  { publicacao: 42000, destaque: 36000, lead: 98000, visita: 31000, comissao: 0, intermediario: 54000, contacto: 18400, concierge: 10000, agencia: 20000 },
  { publicacao: 51500, destaque: 43500, lead: 126000, visita: 38500, comissao: 185000, intermediario: 66000, contacto: 22600, concierge: 15000, agencia: 30000 },
  { publicacao: 60000, destaque: 52500, lead: 151000, visita: 46000, comissao: 96000, intermediario: 78000, contacto: 27800, concierge: 20000, agencia: 30000 },
  { publicacao: 68500, destaque: 61500, lead: 184000, visita: 55500, comissao: 312000, intermediario: 90000, contacto: 31200, concierge: 25000, agencia: 40000 },
  { publicacao: 79000, destaque: 70500, lead: 212000, visita: 64000, comissao: 435000, intermediario: 105000, contacto: 36600, concierge: 30000, agencia: 50000 },
  { publicacao: 87500, destaque: 78000, lead: 238000, visita: 71500, comissao: 520000, intermediario: 117000, contacto: 41000, concierge: 35000, agencia: 60000 },
];

export const FUNNEL_BASE = { pesquisas: 12480, leads: 842, qualificados: 596, visitas: 318, negocios: 21 };
