import type { LucideIcon } from 'lucide-react';
import {
  BedDouble,
  Briefcase,
  Building,
  Coins,
  Construction,
  DoorOpen,
  Hammer,
  Hotel,
  House,
  KeyRound,
  Landmark,
  Layers,
  LayoutGrid,
  Mountain,
  PartyPopper,
  SquareParking,
  Store,
  Tractor,
  TreePalm,
  Warehouse,
} from 'lucide-react';

export const TYPE_ICON: Record<string, LucideIcon> = {
  Apartamento: Building,
  Moradia: House,
  'Casa geminada': Layers,
  Quarto: BedDouble,
  Loja: Store,
  Escritório: Briefcase,
  Armazém: Warehouse,
  'Espaço comercial': LayoutGrid,
  'Salão de eventos': PartyPopper,
  Terreno: Mountain,
  Ruína: Landmark,
  Lodge: Hotel,
  Quinta: Tractor,
  'Terreno na praia': TreePalm,
  'Espaço em aluguer': KeyRound,
  Dependência: DoorOpen,
  Parque: SquareParking,
  Estaleiro: Construction,
  'Imóvel para investimento': Coins,
  'Imóvel para reabilitação': Hammer,
};
